(*!------------------------------------------------------------
 * [[APP_NAME]] ([[APP_URL]])
 *
 * @link      [[APP_REPOSITORY_URL]]
 * @copyright Copyright (c) [[COPYRIGHT_YEAR]] [[COPYRIGHT_HOLDER]]
 * @license   [[LICENSE_URL]] ([[LICENSE]])
 *------------------------------------------------------------- *)

{%dependencies.inc}

{---put your controller-related dependencies registration here---}

container.add('homeController', THomeControllerFactory.create());
container.add('introduceController', TIntroduceControllerFactory.create());
container.add('profileController', TProfileControllerFactory.create());
container.add('unintroduceController', TUnintroduceControllerFactory.create());